---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: fedora-niri-bluebuild
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - atim/starship
        #- zhangyi6324/noctalia-shell
        #- errornointernet/quickshell
        #- brycensranch/gpu-screen-recorder-git
        - lbarrys/cliphist
        #- purian23/matugen
        #- jreilly1821/dms
        - sdegler/hyprland
    install:
      packages:
        - tailscale
        - starship
        #- quickshell
        #- gpu-screen-recorder
        - cliphist
        #- matugen
        #- noctalia-shell
        #- dms
        - niri
        #- fira-code-fonts
        #- jetbrains-mono-fonts-all
        - tlp
        - powertop
        - upower
        - rofi
        - fuzzel
        - sddm-wayland-generic
        ## Multicolor SDDM Theme Dependencies
        - fontawesome-fonts-all
        - impallari-raleway-fonts
        ##
        - waypaper
        - wlogout
        - hyprlock
        - brightnessctl
        - polkit-kde
        - wlsunset
        - cava
        - wl-clipboard
        - qt6-qtmultimedia
        ## Ironbar build dependencies
        #- rust
        #- cargo
        #- gtk4-devel
        #- libadwaita-devel
        #- pkgconf-pkg-config
        #- gcc
        #- make
        #- git
        #- openssl-devel
        #- docker-cli
        ##

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
      - scope: user # Add Flathub user repo, with some user packages
        install:
          - io.missioncenter.MissionCenter
          - org.mozilla.firefox
          - com.brave.Browser
          - com.github.IsmaelMartinez.teams_for_linux
          - com.discordapp.Discord

  - type: fonts
    fonts:
      nerd-fonts:
      - FiraCode # don't add spaces or "Nerd Font" suffix
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
      google-fonts:
      - Roboto
      - Open Sans
      - Inter
      - Fira Sans

  - type: script
    scripts:
      - install-ironbar.sh
      - install-sddm-theme.sh

  - type: systemd
    system:
      enabled:
        - sddm.service
        - tailscaled.service
        - upower.service

  - type: os-release
    properties:
      ID: fedora_em
      ID_LIKE: fedora
      NAME: Fedora Linux Em
      PRETTY_NAME: Fedora Linux Em (Niri Atomic) 

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
